-- Pacientes sin obra social (Sin Cobertura, id=1) pueden acceder a centros públicos
INSERT INTO centro_obra_social_practica (id_centro, id_obra_social, tipo_practica, requiere_autorizacion, dias_estimado_respuesta, activo) VALUES
(1, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (1, 1, 'SALUD_MENTAL', FALSE, 0, TRUE),
(2, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (2, 1, 'SALUD_MENTAL', FALSE, 0, TRUE),
(3, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (3, 1, 'SALUD_MENTAL', FALSE, 0, TRUE),
(4, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (4, 1, 'SALUD_MENTAL', FALSE, 0, TRUE),
(5, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (5, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (5, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(6, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (6, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (6, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(7, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (7, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (7, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(8, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (8, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (8, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(9, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (9, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (9, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(10, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (10, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (10, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(11, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (11, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (11, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(12, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (12, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (12, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(13, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (13, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (13, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(14, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (14, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (14, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(15, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (15, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (15, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE),
(16, 1, 'CONSULTA_AMBULATORIA', FALSE, 0, TRUE), (16, 1, 'SALUD_MENTAL', FALSE, 0, TRUE), (16, 1, 'GUARDIA_EMERGENCIA', FALSE, 0, TRUE);
