ALTER TABLE usuario ADD COLUMN foto_perfil VARCHAR(255) DEFAULT NULL;

ALTER TABLE solicitud ADD COLUMN resumen_breve TEXT DEFAULT NULL;
ALTER TABLE solicitud ADD COLUMN archivo_adjunto VARCHAR(255) DEFAULT NULL;
